# Generated by Django 6.0.4 on 2026-04-09 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=255, verbose_name="Ism familya")),
                ("role", models.CharField(choices=[("milker", "Sut sog'uvchi"), ("shepherd", "Cho'pon"), ("manager", "Ish boshqaruvchi")], max_length=20, verbose_name="Ish turi")),
                ("monthly_salary", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Oylik")),
                ("currency", models.CharField(choices=[("UZS", "UZS"), ("USD", "USD")], default="UZS", max_length=3)),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["full_name"], "verbose_name": "Ishchi", "verbose_name_plural": "Ishchilar"},
        ),
        migrations.CreateModel(
            name="DailyEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_entries", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Kunlik yozuv", "verbose_name_plural": "Kunlik yozuvlar"},
        ),
        migrations.CreateModel(
            name="MilkRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("record_date", models.DateField(unique=True, verbose_name="Sana")),
                ("morning_liters", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Ertalabki sut")),
                ("evening_liters", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Kechki sut")),
                ("price_per_liter", models.DecimalField(decimal_places=2, default=0, help_text="Sut sotuv narxi. Kirim hisoblashda ishlatiladi.", max_digits=12, verbose_name="1 litr narxi")),
                ("currency", models.CharField(choices=[("UZS", "UZS"), ("USD", "USD")], default="UZS", max_length=3)),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="milk_records", to=settings.AUTH_USER_MODEL, verbose_name="Kiritgan foydalanuvchi")),
            ],
            options={"ordering": ["-record_date"], "verbose_name": "Sut yozuvi", "verbose_name_plural": "Sut yozuvlari"},
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("report_type", models.CharField(max_length=100)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("status", models.CharField(choices=[("draft", "Qoralama"), ("ready", "Tayyor"), ("archived", "Arxiv")], default="draft", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reports", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"], "verbose_name": "Hisobot", "verbose_name_plural": "Hisobotlar"},
        ),
        migrations.CreateModel(
            name="FinanceEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_type", models.CharField(choices=[("income", "Kirim"), ("expense", "Chiqim")], max_length=10, verbose_name="Turi")),
                ("category", models.CharField(max_length=120, verbose_name="Kategoriya")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Miqdor")),
                ("currency", models.CharField(choices=[("UZS", "UZS"), ("USD", "USD")], default="UZS", max_length=3)),
                ("source", models.CharField(choices=[("internal", "Ichki hisob"), ("external", "Tashqi hisob")], default="internal", max_length=10, verbose_name="Hisob manbasi")),
                ("entry_date", models.DateField(verbose_name="Sana")),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="finance_entries", to=settings.AUTH_USER_MODEL, verbose_name="Kiritgan foydalanuvchi")),
                ("related_milk_record", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="finance_entries", to="dashboard.milkrecord", verbose_name="Bog'liq sut yozuvi")),
            ],
            options={"ordering": ["-entry_date", "-created_at"], "verbose_name": "Moliyaviy yozuv", "verbose_name_plural": "Moliyaviy yozuvlar"},
        ),
        migrations.CreateModel(
            name="WorkerAdvance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Avans miqdori")),
                ("currency", models.CharField(choices=[("UZS", "UZS"), ("USD", "USD")], default="UZS", max_length=3)),
                ("advance_date", models.DateField(verbose_name="Sana")),
                ("note", models.TextField(blank=True, verbose_name="Izoh")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="worker_advances", to=settings.AUTH_USER_MODEL)),
                ("worker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="advances", to="dashboard.worker", verbose_name="Ishchi")),
            ],
            options={"ordering": ["-advance_date", "-created_at"], "verbose_name": "Ishchi avansi", "verbose_name_plural": "Ishchi avanslari"},
        ),
        migrations.CreateModel(
            name="ReportItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary_value", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="report_items", to="dashboard.dailyentry")),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="dashboard.report")),
            ],
            options={"verbose_name": "Hisobot qatori", "verbose_name_plural": "Hisobot qatorlari", "unique_together": {("report", "entry")}},
        ),
    ]
