# Generated by Django 6.0.4 on 2026-04-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslink',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vaqtinchalik havola', 'verbose_name_plural': 'Vaqtinchalik havolalar'},
        ),
        migrations.AlterModelOptions(
            name='allowedcontact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ruxsat berilgan kontakt', 'verbose_name_plural': 'Ruxsat berilgan kontaktlar'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit log', 'verbose_name_plural': 'Audit loglar'},
        ),
        migrations.AlterModelOptions(
            name='telegramsession',
            options={'ordering': ['-last_seen_at'], 'verbose_name': 'Telegram sessiya', 'verbose_name_plural': 'Telegram sessiyalar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['full_name', 'username'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterField(
            model_name='allowedcontact',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='allowedcontact',
            name='phone_number',
            field=models.CharField(help_text='Masalan: +998901234567', max_length=20, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='allowedcontact',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('manager', 'Menejer'), ('admin', 'Administrator')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Masalan: +998901234567', max_length=20, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('manager', 'Menejer'), ('admin', 'Administrator')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Botdagi birinchi kirish uchun foydalanuvchiga beriladigan login.', max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
